import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@/styles/Blog.module.scss'
import blogIntro from 'assets/images/blog.png'
import blogList from 'assets/images/blog-list.png'
import blogAnswer from 'assets/images/blog-answer.png'

const Blog = () => {

    return (
        <>
            <Head>
                <title>TOTC-Blog</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
            </Head>
            <main>
                <section id='blog' className={styles.blog}>
                    <div className='container'>
                        <div className={styles.container}>
                            <div className={styles.container__left}>
                                <p className={styles.container__left__disc}>By Themadbrains in inspiration</p>
                                <h2 className={styles.container__left__title}>Why Swift UI Should Be on the Radar of Every Mobile Developer</h2>
                                <p className={styles.container__left__text}>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempos Lorem ipsum dolor sitamet, consectetur adipiscing elit, sed do eiusmod tempor</p>
                                <button className={styles.container__left__btn}>Start learning now</button>
                            </div>
                            <div className={styles.container__right}>
                                <Image className={styles.container__right__img}
                                    src={blogIntro}
                                    alt='img-intro'
                                    width={779}
                                    height={526}
                                />
                            </div>
                        </div>
                    </div>
                </section>
                <section className={styles.blog_list}>
                    <div className="container">
                        <div className={styles.container}>
                            <h2 className={styles.container__title}>Reading blog list</h2>
                            <ul className={styles.container__list}>
                                <button className={styles.container__list__item}>
                                    <Image className={styles.container__list__item__img}
                                        src={blogList}
                                        alt='img-blog-list'
                                        width={200}
                                        height={200}
                                    />
                                    <p className={styles.container__list__item__title}>React</p>
                                </button>
                                <button className={styles.container__list__item}>
                                    <Image className={styles.container__list__item__img}
                                        src={blogList}
                                        alt='img-blog-list'
                                        width={200}
                                        height={200}
                                    />
                                    <p className={styles.container__list__item__title}>React</p>
                                </button>
                                <button className={styles.container__list__item}>
                                    <Image className={styles.container__list__item__img}
                                        src={blogList}
                                        alt='img-blog-list'
                                        width={200}
                                        height={200}
                                    />
                                    <p className={styles.container__list__item__title}>React</p>
                                </button>
                                <button className={styles.container__list__item}>
                                    <Image className={styles.container__list__item__img}
                                        src={blogList}
                                        alt='img-blog-list'
                                        width={200}
                                        height={200}
                                    />
                                    <p className={styles.container__list__item__title}>React</p>
                                </button>
                            </ul>
                        </div>
                    </div>
                </section>
                <section className={styles.blog_answer}>
                    <div className="container">
                        <div className={styles.container}>
                            <ul className={styles.container__list1}>
                                <li className={styles.container__list1__item}>Related Blog </li>
                                <li className={styles.container__list1__item}><button>See all</button></li>
                            </ul>
                            <ul className={styles.container__list2}>
                                <li className={styles.container__list2__item}>
                                    <Image className={styles.container__list2__item__img}
                                        src={blogAnswer}
                                        alt='blog-answer'
                                        width={200}
                                        height={200}
                                    />
                                    <h2>Class adds $30 million to its balance sheet for a Zoom-friendly edtech solution</h2>
                                    <b>
                                        <Image />
                                        <p>Jony</p>
                                    </b>
                                    <p>Class, launched less than a year ago by Blackboard co-founder Michael Chasen, integrates exclusively...</p>
                                </li>
                            </ul>
                            <ul>
                                <li>
                                    <Link href='/'>
                                        <button>Read more</button>
                                    </Link>
                                </li>
                                <li>
                                    <i className="bi bi-eye-fill"></i>
                                    <p>251,232</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </section>
            </main>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        </>
    )
}

export default Blog;