import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.scss'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const ourData = [
    {
      id: 1,
      number: '15K+',
      title: 'Students'
    },
    {
      id: 2,
      number: '75%',
      title: 'Total success'

    },
    {
      id: 3,
      number: '35',
      title: 'Main questions'
    },
    {
      id: 4,
      number: '26',
      title: 'Chief experts'
    },
    {
      id: 5,
      number: '16',
      title: 'Years of experience'
    },
  ]
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>
        <div className={styles.container}>
          <div className={styles.home__inner}>
            <div>
              <h1>Studying Online is now much easier</h1>
              <p>TOTC is an interesting platform that will teach you in more an interactive way</p>
              <span>
                <Link href=''>
                  <button>Join free</button>
                </Link>
                <Link href=''>
                  <button>
                    <h5>
                      <Image src='/image/play__foto.svg' alt='play foto' width={40} height={40} />
                    </h5>
                    <h6>Watch how it works</h6>
                  </button>
                </Link>
              </span>
            </div>

            <ul>
              <li>
                <Image src='/image/progress.svg' alt='progress' width={89} height={89} />
              </li>
              <li>
                <Image src='/image/calendar.svg' alt='progress' width={49} height={49} />
                <span>
                  <h6><b>250K</b></h6>
                  <p>Assisted Student</p>
                </span>
              </li>
              <li>
                <Image src='/image/message.svg' alt='progress' width={49} height={49} />
                <span>
                  <h6>Congratulations</h6>
                  <p>Your admission completed</p>
                </span>
              </li>
              <li>
                <b>
                  <Image src='/image/odamcha.svg' alt='progress' width={49} height={49} />
                </b>
                <span>
                  <h6>User Experience Class</h6>
                  <p>Today at 12.00 PM</p>
                  <Link href='/'>
                    <button>Join Now</button>
                  </Link>
                </span>
              </li>

            </ul>
          </div>
        </div>
      </div>

      <div className={styles.main}>
        <div className={styles.container}>
          <div className={styles.main__inner}>
            <h3>Our Success</h3>
            <p>Ornare id fames interdum porttitor nulla turpis etiam. Diam vitae sollicitudin at nec nam et pharetra gravida. Adipiscing a quis ultrices eu ornare tristique vel nisl orci. </p>
            <ul>
              {
                ourData?.map((e) => (
                  <li key={e.id}>
                    <h4>{e.number}</h4>
                    <p>{e.title}</p>

                  </li>
                ))
              }
            </ul>
          </div>

          <div className={styles.main__mainner}>
            <h4>All-In-One <span>Cloud Software.</span></h4>
            <p>TOTC is one powerful online software suite that combines all the tools needed to run a successful school or office.
            </p>
            <ul>
              <li>
                <div className={styles.divcha}>
                  <div className="img">
                    <Image src='/image/document.svg' alt='document' width={33} height={46} />
                  </div>
                  <h5>Online Billing, Invoicing, & Contracts</h5>
                  <p>Simple and secure control of your organization’s financial and legal transactions. Send customized invoices and contracts</p>
                </div>
              </li>
              <li>
                <div className={styles.divcha}>
                  <div className="img">
                    <Image src='/image/user.svg' alt='document' width={55} height={44} />
                  </div>
                  <h5>Easy Scheduling & Attendance Tracking</h5>
                  <p>Schedule and reserve classrooms at one campus or multiple campuses. Keep detailed records of student attendance</p>
                </div>
              </li>
              <li>
                <div className={styles.divcha}>
                  <div className="img">
                    <Image src='/image/document.svg' alt='document' width={33} height={46} />
                  </div>
                  <h5>Customer Tracking</h5>
                  <p>Automate and track emails to individuals or groups. Skilline’s built-in system helps organize your organization </p>
                </div >
              </li>
            </ul>
          </div>
        </div>

        <div className={styles.totc}>
          <div>
            <h2>What is <span>TOTC?</span></h2>
            <p>TOTC is a platform that allows educators to create online classes whereby they can store the course materials online; manage assignments, quizzes and exams; monitor due dates; grade results and provide students with feedback all in one place.</p>
            <ul>
              <li>
                <h3>FOR INSTRUCTORS</h3>
                <button>Start a class today</button>
              </li>
              <li>
                <h3>FOR STUDENTS</h3>
                <button>Enter access code</button>
              </li>
            </ul>
          </div>
        </div>

        <div className={styles.everything}>
          <ul>
            <li>
              <div>
                <h2>Everything you can do in a physical classroom, <span>you can do with TOTC</span></h2>
                <p>TOTC’s school management software helps traditional and online schools manage scheduling, attendance, payments and virtual classrooms all in one secure cloud-based system.</p>
                <Link href='/'>Learn more</Link>
              </div>
            </li>
            <li>
              <Image src='/image/video__play.svg' alt='video' width={705} height={470} />
            </li>
          </ul>
        </div>

        <div className={styles.feature}>
          <span>
            <h3>Our <b>Features</b></h3>
            <p>This very extraordinary feature, can make learning activities more efficient</p>
            <ul>
              <li className={styles.lillar}>
                <h5>
                  <Image src='image/Howard.svg' alt='rasm' width={255} height={246} />
                  <h6>
                    <button>Present</button>
                    <button>End the Call</button>
                  </h6>
                </h5>
                <h5>
                  <Image src='image/Tamara.svg' alt='rasm' width={166} height={160} />
                  <Image src='image/Humbert.svg' alt='rasm' width={166} height={160} />
                </h5>
                <h5>
                  <Image src='image/Adam.svg' alt='rasm' width={202} height={195} />
                  <Image src='image/Patrica.svg' alt='rasm' width={240} height={232} />
                </h5>
              </li>
              <li>
                <h4>A <b>user interface</b> designed for the classroom</h4>
                <ul>
                  <li>
                    <h6>
                      <Image src='/image/menu.svg' width={26} height={26} alt='rasmca' />
                    </h6>
                    <p>Teachers don’t get lost in the grid view and have a dedicated Podium space.</p>
                  </li>
                  <li>
                    <h6>
                      <Image src='/image/menu__second.svg' width={28} height={26} alt='rasmca' />
                    </h6>
                    <p>TA’s and presenters can be moved to the front of the class.</p>
                  </li>
                  <li>
                    <h6>
                      <Image src='/image/menu__third.svg' width={30} height={26} alt='rasmca' />
                    </h6>
                    <p>Teachers can easily see all students and class data at one time.</p>
                  </li>
                </ul>
              </li>
            </ul>
          </span>
        </div>

        <div className={styles.tools}>
          <div className={styles.tools__inner}>
            <ul>
              <li>
                <h2><b>Tools</b> For Teachers And Learners</h2>
                <p>Class has a dynamic set of teaching tools built to be deployed and used during class.
                  Teachers can handout assignments in real-time for students to complete and submit.</p>
              </li>
              <li>
                <h3>
                  <h5></h5>
                  <Image src='/image/qizcha__one.svg' alt='d' width={86} height={86} />
                  <Image src='/image/qizcha__two.svg' className={styles.rasm} alt='d' width={86} height={86} />
                </h3>
              </li>
            </ul>
          </div>
        </div>

        <div className={styles.questions}>
          <div className={styles.questions__inner}>
            <ul>
              <li>
                <h4>Question 1</h4>
                <h3>True or false? This play takes place in Italy</h3>
                <Image src='/image/sohil.svg' alt='rasm' width={450} height={255} />
                <span>
                  <Image src='/image/samolyot.svg' alt='1234' width={50} height={50} />
                  <p>Your answer was sent successfully</p>
                </span>
              </li>
              <li>
                <h2>Assessments, <b>Quizzes</b>, Tests</h2>
                <p>Easily launch live assignments, quizzes, and tests.Student results are automatically entered in the online gradebook.</p>
              </li>
            </ul>
          </div>
        </div>

        <div className={styles.management}>
          <div className={styles.management__inner}>
            <ul>
              <li>
                <h2><b>Class Management</b> Tools for Educators</h2>
                <p>Class provides tools to help run and manage the class such as Class Roster, Attendance, and more. With the Gradebook, teachers can review and grade tests and quizzes in real-time.</p>
              </li>
              <li>
                <Image src='/image/gradebook.svg' alt='gradebook' width={808} height={560} />
              </li>
            </ul>
            <ul>
              <li>
                <h2>One-on-One <b>Discussions</b></h2>
                <p>Teachers and teacher assistants can talk with students privately without leaving the Zoom environment.</p>
              </li>
              <li>
                <Image src='/image/gradebook2.svg' alt='gradebook' width={755} height={500} />
              </li>
            </ul>
            <Link href='/'><button>See more features</button></Link>
          </div>
        </div>


        <div className={styles.sliders}>
          <div className={styles.sliders__inner}>
            <div className={styles.sliders__inner__head}>
              <h2>Explore Course</h2>
              <p>Ut sed eros finibus, placerat orci id, dapibus.</p>
              <span>
                <h5>Lorem Ipsum</h5>
                <Link href='/'>See All</Link>
              </span>
              <ul>
                <li>
                  <h1>
                    <h3>boooks</h3>
                  </h1>
                  <Image src='/image/qizcha.svg' alt='sada' width={200} height={400} />
                  <b>
                    <h6>Lorem ipsum dolor sit amet.</h6>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima perferendis repellendus quam laborum, cumque expedita!</p>
                    <h4>$450</h4>
                    <button>EXPLORE</button>
                  </b>
                </li>
                <li>
                  <h1>
                    <h3>boooks</h3>
                  </h1>
                  <Image src='/image/qizcha.svg' alt='sada' width={200} height={400} />
                  <b>
                    <h6>Lorem ipsum dolor sit amet.</h6>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima perferendis repellendus quam laborum, cumque expedita!</p>
                    <h4>$450</h4>
                    <button>EXPLORE</button>
                  </b>
                </li>
                <li>
                  <h1>
                    <h3>boooks</h3>
                  </h1>
                  <Image src='/image/qizcha.svg' alt='sada' width={200} height={400} />
                  <b>
                    <h6>Lorem ipsum dolor sit amet.</h6>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima perferendis repellendus quam laborum, cumque expedita!</p>
                    <h4>$450</h4>
                    <button>EXPLORE</button>
                  </b>
                </li>
                <li>
                  <h1>
                    <h3>boooks</h3>
                  </h1>
                  <Image src='/image/qizcha.svg' alt='sada' width={200} height={400} />
                  <b>
                    <h6>Lorem ipsum dolor sit amet.</h6>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima perferendis repellendus quam laborum, cumque expedita!</p>
                    <h4>$450</h4>
                    <button>EXPLORE</button>
                  </b>
                </li>

                <li>
                  <h1>
                    <h3>boooks</h3>
                  </h1>
                  <Image src='/image/qizcha.svg' alt='sada' width={200} height={400} />
                  <b>
                    <h6>Lorem ipsum dolor sit amet.</h6>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima perferendis repellendus quam laborum, cumque expedita!</p>
                    <h4>$450</h4>
                    <button>EXPLORE</button>
                  </b>
                </li>
                <li>
                  <h1>
                    <h3>boooks</h3>
                  </h1>
                  <Image src='/image/qizcha.svg' alt='sada' width={200} height={400} />
                  <b>
                    <h6>Lorem ipsum dolor sit amet.</h6>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima perferendis repellendus quam laborum, cumque expedita!</p>
                    <h4>$450</h4>
                    <button>EXPLORE</button>
                  </b>
                </li>
              </ul>

              <span>
                <h5>Lorem Ipsum</h5>
                <Link href='/'>See All</Link>
              </span>
              <ul>
                <li>
                  <h1>
                    <h3>Anime</h3>
                  </h1>
                  <Image src='/image/qizcha.svg' alt='sada' width={200} height={400} />
                  <b>
                    <h6>Lorem ipsum dolor sit amet.</h6>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima perferendis repellendus quam laborum, cumque expedita!</p>
                    <h4>$450</h4>
                    <button>EXPLORE</button>
                  </b>
                </li>
                <li>
                  <h1>
                    <h3>Anime</h3>
                  </h1>
                  <Image src='/image/qizcha.svg' alt='sada' width={200} height={400} />
                  <b>
                    <h6>Lorem ipsum dolor sit amet.</h6>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima perferendis repellendus quam laborum, cumque expedita!</p>
                    <h4>$450</h4>
                    <button>EXPLORE</button>
                  </b>
                </li>
                <li>
                  <h1>
                    <h3>Anime</h3>
                  </h1>
                  <Image src='/image/qizcha.svg' alt='sada' width={200} height={400} />
                  <b>
                    <h6>Lorem ipsum dolor sit amet.</h6>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima perferendis repellendus quam laborum, cumque expedita!</p>
                    <h4>$450</h4>
                    <button>EXPLORE</button>
                  </b>
                </li>
                <li>
                  <h1>
                    <h3>Anime</h3>
                  </h1>
                  <Image src='/image/qizcha.svg' alt='sada' width={200} height={400} />
                  <b>
                    <h6>Lorem ipsum dolor sit amet.</h6>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima perferendis repellendus quam laborum, cumque expedita!</p>
                    <h4>$450</h4>
                    <button>EXPLORE</button>
                  </b>
                </li>

                <li>
                  <h1>
                    <h3>Anime</h3>
                  </h1>
                  <Image src='/image/qizcha.svg' alt='sada' width={200} height={400} />
                  <b>
                    <h6>Lorem ipsum dolor sit amet.</h6>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima perferendis repellendus quam laborum, cumque expedita!</p>
                    <h4>$450</h4>
                    <button>EXPLORE</button>
                  </b>
                </li>
                <li>
                  <h1>
                    <h3>Anime</h3>
                  </h1>
                  <Image src='/image/qizcha.svg' alt='sada' width={200} height={400} />
                  <b>
                    <h6>Lorem ipsum dolor sit amet.</h6>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima perferendis repellendus quam laborum, cumque expedita!</p>
                    <h4>$450</h4>
                    <button>EXPLORE</button>
                  </b>
                </li>
                <li>
                  <h1>
                    <h3>Anime</h3>
                  </h1>
                  <Image src='/image/qizcha.svg' alt='sada' width={200} height={400} />
                  <b>
                    <h6>Lorem ipsum dolor sit amet.</h6>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima perferendis repellendus quam laborum, cumque expedita!</p>
                    <h4>$450</h4>
                    <button>EXPLORE</button>
                  </b>
                </li>
                <li>
                  <h1>
                    <h3>Anime</h3>
                  </h1>
                  <Image src='/image/qizcha.svg' alt='sada' width={200} height={400} />
                  <b>
                    <h6>Lorem ipsum dolor sit amet.</h6>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima perferendis repellendus quam laborum, cumque expedita!</p>
                    <h4>$450</h4>
                    <button>EXPLORE</button>
                  </b>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

    </>
  )
}
